name: rustplayer
version: '1.1.4-1'
summary: A local music player && network radio player
description: |
  RustPlayer is a local music player && network radio player:

base: core20
confinement: strict

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el

parts:
  rustplayer:
    plugin: rust
    source: .
    override-pull: |
      snapcraftctl pull
      git submodule update --init --recursive
    build-packages:
      - pkg-config
      - libssl-dev
      - clang
      - git
      - nasm
      - yasm
      - libclang-dev
      - libasound2-dev
    stage-packages:
      - libasound2

layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

apps:
  rustplayer:
    command: bin/rustplayer
    plugs:
      - network
      - audio-playback
      - home
      # connect manually
      - pulseaudio
      - alsa
      - removable-media
